"""Game-phase and research/execution agents."""

from . import (  # noqa: F401
    autopilot,
    backtest,
    baseline,
    book_watch,
    candidate_ranker,
    closing_snapshot,
    daily_cycle,
    demo_execute,
    discover_markets,
    heartbeat,
    health_check,
    historical_backtest,
    lineups,
    live_execute,
    lock,
    market_matcher,
    monitor,
    news_ingest,
    news_watch,
    order_reconcile,
    paper,
    ports,
    portfolio_sync,
    qual_index,
    qual_postmortem,
    qual_research,
    reconcile,
    research_agent,
    scheduled_demo_cycle,
    settlement_audit,
    slate_discovery,
    slate_verify,
    snapshot_market,
    source_check,
    status,
    telegram_test,
    ui,
    validation_report,
)

PHASES = {
    "autopilot": autopilot.run,
    "backtest": backtest.run,
    "baseline": baseline.run,
    "book-watch": book_watch.run,
    "candidate-ranker": candidate_ranker.run,
    "closing-snapshot": closing_snapshot.run,
    "daily-cycle": daily_cycle.run,
    "demo-execute": demo_execute.run,
    "discover-markets": discover_markets.run,
    "lineups": lineups.run,
    "live-execute": live_execute.run,
    "lock": lock.run,
    "heartbeat": heartbeat.run,
    "health-check": health_check.run,
    "historical-backtest": historical_backtest.run,
    "live": heartbeat.run,      # alias so a plain crontab can drive the live loop
    "market-matcher": market_matcher.run,
    "monitor": monitor.run,
    "news-ingest": news_ingest.run,
    "news-watch": news_watch.run,
    "order-reconcile": order_reconcile.run,
    "paper": paper.run,
    "ports": ports.run,
    "portfolio-sync": portfolio_sync.run,
    "qual-index": qual_index.run,
    "qual-postmortem": qual_postmortem.run,
    "qual-research": qual_research.run,
    "reconcile": reconcile.run,
    "research-agent": research_agent.run,
    "scheduled-demo-cycle": scheduled_demo_cycle.run,
    "settlement-audit": settlement_audit.run,
    "slate-discovery": slate_discovery.run,
    "slate-verify": slate_verify.run,
    "snapshot-market": snapshot_market.run,
    "source-check": source_check.run,
    "status": status.run,
    "telegram-test": telegram_test.run,
    "ui": ui.run,
    "validation-report": validation_report.run,
}
